### ISSUE TITLE
Demo scrolling is borked on Macs

### ISSUE THREAD

**Issue by domenic** [domenic/html-as-custom-elements#42]
Reported by @addyosmani at https://twitter.com/domenic/status/546062775961661440

I don't have easy access to a Mac so I'd love it if someone could take a stab at a pull request. We might get a Chrome bug out of this.

**Comment by vigneshshanmugam** [comment]
Reproduced this issue on my mac. 

Chrome : 41.0.2251.0 canary (64-bit)
Mac Os : OS X 10.9.4

Will take a look.

**Comment by vigneshshanmugam** [comment]
Fixed.

https://github.com/domenic/html-as-custom-elements/pull/45
